/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import presentacion.panel.PanelCuentas;
import presentacion.panel.PanelReporteCategoria;
import presentacion.panel.PanelReporteIngVsEgr;
import presentacion.panel.PanelReportePeriodo;

/**
 *
 * @author rfcas
 */
public class Vista extends javax.swing.JFrame {

    private Modelo modelo;
    private Controlador controlador;

    /**
     * Creates new form Vista
     */
    public Vista(Modelo modelo) {
        super();
        this.controlador = new Controlador(this);
        this.modelo = modelo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelTransacciones = new javax.swing.JPanel();
        jPanelCuenta = new javax.swing.JPanel();
        jPanelCuentas = new PanelCuentas(this);
        jPanelNuevaCuenta = new presentacion.panel.PanelCrearCuenta(modelo);
        jPanelMovimiento = new javax.swing.JPanel();
        jPanelMovimientos = new presentacion.panel.PanelMovimientos(this);
        jPanelNuevoMovimiento = new presentacion.panel.PanelCrearMovimiento(modelo);
        jPanelReportes = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelRepCategoria = new PanelReporteCategoria(modelo);
        jPanelRepPeriodo = new PanelReportePeriodo(modelo);
        jPanelInvVsEgr = new PanelReporteIngVsEgr(modelo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi Billetera");
        setMaximumSize(new java.awt.Dimension(3000, 2000));
        setMinimumSize(new java.awt.Dimension(300, 200));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanelTransacciones.setLayout(new java.awt.GridLayout(0, 1));

        jPanelCuenta.setPreferredSize(new java.awt.Dimension(800, 150));
        jPanelCuenta.setLayout(new java.awt.GridLayout(1, 0));

        jPanelCuentas.setLayout(new javax.swing.BoxLayout(jPanelCuentas, javax.swing.BoxLayout.Y_AXIS));
        jPanelCuenta.add(jPanelCuentas);
        jPanelCuenta.add(jPanelNuevaCuenta);

        jPanelTransacciones.add(jPanelCuenta);

        jPanelMovimiento.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        jPanelMovimientos.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimientos"));
        jPanelMovimiento.add(jPanelMovimientos);

        jPanelNuevoMovimiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo movimiento"));
        jPanelMovimiento.add(jPanelNuevoMovimiento);

        jPanelTransacciones.add(jPanelMovimiento);

        jTabbedPane1.addTab("Transacciones", jPanelTransacciones);

        jPanelReportes.setLayout(new javax.swing.OverlayLayout(jPanelReportes));

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });
        jTabbedPane2.addTab("Por categoria", jPanelRepCategoria);
        jTabbedPane2.addTab("Por periodo", jPanelRepPeriodo);
        jTabbedPane2.addTab("Ingresos vs Egresos", jPanelInvVsEgr);

        jPanelReportes.add(jTabbedPane2);

        jTabbedPane1.addTab("Reportes", jPanelReportes);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>


    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        JTabbedPane tabbedPane = (JTabbedPane) evt.getSource();
        JPanel panelSelected = (JPanel) tabbedPane.getSelectedComponent();
        if (panelSelected instanceof PanelReporteIngVsEgr) {
            ActionEvent ae = new ActionEvent(this, 0, Eventos.CALCULAR_REPORTE_INGVSEGR.toString());
            this.getControlador().actionPerformed(ae);
        }
    }//GEN-LAST:event_jTabbedPane2StateChanged

    public Controlador getControlador() {
        return this.controlador;
    }

    public Modelo getModelo() {
        return this.modelo;
    }

    public void showDialog(String title, String message, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCuenta;
    private javax.swing.JPanel jPanelCuentas;
    private javax.swing.JPanel jPanelInvVsEgr;
    private javax.swing.JPanel jPanelMovimiento;
    private javax.swing.JPanel jPanelMovimientos;
    private javax.swing.JPanel jPanelNuevaCuenta;
    private javax.swing.JPanel jPanelNuevoMovimiento;
    private javax.swing.JPanel jPanelRepCategoria;
    private javax.swing.JPanel jPanelRepPeriodo;
    private javax.swing.JPanel jPanelReportes;
    private javax.swing.JPanel jPanelTransacciones;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jPanelCuentas
     */
    public javax.swing.JPanel getjPanelCuentas() {
        return jPanelCuentas;
    }

    /**
     * @return the jPanelNuevaCuenta
     */
    public javax.swing.JPanel getjPanelNuevaCuenta() {
        return jPanelNuevaCuenta;
    }

    public JPanel getjPanelMovimientos() {
        return jPanelMovimientos;
    }

    public JPanel getjPanelNuevoMovimiento() {
        return jPanelNuevoMovimiento;
    }

    public JPanel getjPanelInvVsEgr() {
        return jPanelInvVsEgr;
    }

    public JPanel getjPanelRepCategoria() {
        return jPanelRepCategoria;
    }

    public JPanel getjPanelRepPeriodo() {
        return jPanelRepPeriodo;
    }

}
