/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.panel;

import javax.swing.JTextField;
import presentacion.Vista;

/**
 *
 * @author rfcas
 */
public class PanelReporteIngVsEgr extends javax.swing.JPanel {

    private Vista vista;
    
    /**
     * Creates new form PanelReporteIngVsEgr
     */
    public PanelReporteIngVsEgr(Vista vista) {
        super();
        this.vista = vista;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldIngresos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEgresos = new javax.swing.JTextField();

        jLabel1.setText("Ingresos");
        add(jLabel1);

        jTextFieldIngresos.setColumns(15);
        jTextFieldIngresos.setText("0");
        add(jTextFieldIngresos);

        jLabel2.setText("Egresos");
        add(jLabel2);

        jTextFieldEgresos.setColumns(15);
        jTextFieldEgresos.setText("0");
        add(jTextFieldEgresos);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldEgresos;
    private javax.swing.JTextField jTextFieldIngresos;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextFieldEgresos() {
        return jTextFieldEgresos;
    }

    public JTextField getjTextFieldIngresos() {
        return jTextFieldIngresos;
    }

    

}
